name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - flake8
  - types-decorator
  - mypy
  - numpy==1.23.4
  - pytest
  - tqdm
  - librosa >= 0.8
  - numpy >= 1.16
  - requests
  - pandas

  - pip:
    - jams