name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - flake8==6.0.0
  - librosa==0.10.0
  - mypy==1.3.0
  - numpy==1.23.1
  - pandas==2.0.2
  - pytest==7.3.1
  - requests==2.31.0
  - tqdm==4.65.0
  - types-decorator==5.1.8.3

  - pip:
    - jams==0.3.4