name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required for linting and static type checking
  - pip
  - flake8>=5.0.4
  - mypy>=0.982
  - types-decorator>=5.1.8.3

  - pip:
    - jams>=0.3.4