name: Docs preview PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions: write-all
jobs:
  docs:
    name: Build docs preview on PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1-dev
        pip install docutils==0.16 numpydoc recommonmark sphinx>=3.4.0  sphinxcontrib-napoleon sphinx_rtd_theme sphinx-togglebutton

    - name: Sphinx build
      run: |
        sphinx-build docs _build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
        destination_dir: preview/PR-${{ github.event.number }}
